server {
    listen 80;
    server_name attendance-system-pnc.site www.attendance-system-pnc.site;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name attendance-system-pnc.site www.attendance-system-pnc.site;
    root /var/www/html/public;
    index index.php;

    ssl_certificate /etc/letsencrypt/live/attendance-system-pnc.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/attendance-system-pnc.site/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass backend:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known) {
        return 404;
    }
}