<?php

namespace Database\Seeders;

use App\Models\Student;
use App\Models\StudentClass;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $class = StudentClass::first();

        if (!$class) {
            return;
        }

        $students = [
            
            [
                'student_code' => 'PNC2026-037',
                'first_name' => 'Serey',
                'last_name' => 'Phem',
                'fullname' => 'Serey Phem',
                'username' => 'serey.phem',
                'email' => 'serey.phem@student.passerellesnumeriques.org',
                'gender' => 'Male',
                'date_of_birth' => '2006-02-12',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2026-037.png',
                'card_id' => 'PNC2026-037',
                'face_image' => 'faces/pnc2026037.jpg',
                'parent_number' => '+855 12 345 678',
                'contact' => '+855 12 345 678',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2026-053',
                'first_name' => 'Vichet',
                'last_name' => 'Sat',
                'fullname' => 'Vichet Sat',
                'username' => 'vichet.sat',
                'email' => 'vichet.sat@student.passerellesnumeriques.org',
                'gender' => 'Male',
                'date_of_birth' => '2007-05-12',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2026-053.png',
                'card_id' => 'PNC2026-053',
                'face_image' => 'faces/pnc2026053.jpg',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2026-049',
                'first_name' => 'Sreyroth',
                'last_name' => 'Sang',
                'fullname' => 'Sreyroth Sang',
                'username' => 'sreyroth.sang',
                'email' => 'sreyroth.sang@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2007-06-11',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2026-049.png',
                'card_id' => 'PNC2026-049',
                'face_image' => 'faces/pnc2026049.jpg',
                'parent_number' => '+855 98 765 432',
                'contact' => '+855 98 765 432',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2026-051',
                'first_name' => 'Mary',
                'last_name' => 'Sao',
                'fullname' => 'Mary Sao',
                'username' => 'mary.sao',
                'email' => 'mary.sao@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2006-07-21',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2026-051.png',
                'card_id' => 'PNC2026-051',
                'face_image' => 'faces/pnc2026051.jpg',
                'parent_number' => '+855 98 779 999',
                'contact' => '+855 98 765 431',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2026-020',
                'first_name' => 'Vakhim',
                'last_name' => 'Krean',
                'fullname' => 'Vakhim Krean',
                'username' => 'vakhim.krean',
                'email' => 'vakhim.krean@student.passerellesnumeriques.org',
                'gender' => 'Male',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2026-020.png',
                'card_id' => 'PNC2026-020',
                'face_image' => 'faces/pnc2026020.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-002',
                'first_name' => 'Thyda',
                'last_name' => 'Ang',
                'fullname' => 'Thyda Ang',
                'username' => 'thyda.ang',
                'email' => 'thyda.ang@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-002.png',
                'card_id' => 'PNC2027-002',
                'face_image' => 'faces/pnc2027002.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-049',
                'first_name' => 'Sreyrath',
                'last_name' => 'Chan',
                'fullname' => 'ChanSreyrath Morm',
                'username' => 'chansreyrath.morm',
                'email' => 'chansreyrath.morm@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-049.png',
                'card_id' => 'PNC2027-049',
                'face_image' => 'faces/pnc2027049.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2026-011',
                'first_name' => 'Sreypov',
                'last_name' => 'Hut',
                'fullname' => 'Sreypov Hut',
                'username' => 'sreypov.hut',
                'email' => 'sreypov.hut@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2026-011.png',
                'card_id' => 'PNC2026-011',
                'face_image' => 'faces/pnc2026011.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-010',
                'first_name' => 'soklin',
                'last_name' => 'chork',
                'fullname' => 'soklin chork',
                'username' => 'soklin.chork',
                'email' => 'soklin.chork@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-010.png',
                'card_id' => 'PNC2027-010',
                'face_image' => 'faces/pnc2027010.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-017',
                'first_name' => 'Youra',
                'last_name' => 'Dome',
                'fullname' => 'Youra Dome',
                'username' => 'youra.dome',
                'email' => 'youra.dome@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-017.png',
                'card_id' => 'PNC2027-017',
                'face_image' => 'faces/pnc2027017.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-072',
                'first_name' => 'Sokyi',
                'last_name' => 'Koy',
                'fullname' => 'Sokyi Koy',
                'username' => 'sokyi.koy',
                'email' => 'sokyi.koy@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-072.png',
                'card_id' => 'PNC2027-072',
                'face_image' => 'faces/pnc2027072.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-094',
                'first_name' => 'Saory',
                'last_name' => 'Thorn',
                'fullname' => 'Saory thorn',
                'username' => 'saory.thorn',
                'email' => 'saory.thorn@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-094.png',
                'card_id' => 'PNC2027-094',
                'face_image' => 'faces/pnc2027094.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-060',
                'first_name' => 'Somaly',
                'last_name' => 'Thorn',
                'fullname' => 'Somaly Ren',
                'username' => 'somaly.ren',
                'email' => 'somaly.ren@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-060.png',
                'card_id' => 'PNC2027-060',
                'face_image' => 'faces/pnc2027060.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-074',
                'first_name' => 'Somin',
                'last_name' => 'Met',
                'fullname' => 'Somin Met',
                'username' => 'somin.met',
                'email' => 'somin.met@student.passerellesnumeriques.org',
                'gender' => 'Male',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-074.png',
                'card_id' => 'PNC2027-074',
                'face_image' => 'faces/pnc2027074.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-050',
                'first_name' => 'Soriya',
                'last_name' => 'Mut',
                'fullname' => 'Soriya Mut',
                'username' => 'soriya.mut',
                'email' => 'soriya.mut@student.passerellesnumeriques.org',
                'gender' => 'Male',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-050.png',
                'card_id' => 'PNC2027-050',
                'face_image' => 'faces/pnc2027050.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-061',
                'first_name' => 'Narong',
                'last_name' => 'Rieng',
                'fullname' => 'Narong Rieng',
                'username' => 'narong.rieng',
                'email' => 'narong.rieng@student.passerellesnumeriques.org',
                'gender' => 'Male',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-061.png',
                'card_id' => 'PNC2027-061',
                'face_image' => 'faces/pnc2027061.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
            [
                'student_code' => 'PNC2027-008',
                'first_name' => 'Dalin',
                'last_name' => 'Chhoeurn',
                'fullname' => 'Dalin Chhoeurn',
                'username' => 'dalin.chhoeurn',
                'email' => 'dalin.chhoeurn@student.passerellesnumeriques.org',
                'gender' => 'Female',
                'date_of_birth' => '2004-05-29',
                'class_id' => $class->id,
                'qr_code' => 'qr_pnc2027-008.png',
                'card_id' => 'PNC2027-008',
                'face_image' => 'faces/pnc2027008.jpg',
                'parent_number' => '+855 98 997 777',
                'contact' => '+855 98 765 434',
                'is_active' => true,
            ],
        ];

        foreach ($students as $studentData) {
            Student::updateOrCreate(
                ['student_code' => $studentData['student_code']],
                $studentData
            );
        }

        $testStudentId = Student::where('student_code', 'TEST-001')->value('id');
        $studentRoleId = DB::table('roles')
            ->whereRaw('LOWER(name) = ?', ['student'])
            ->value('id');

        if ($testStudentId && $studentRoleId) {
            DB::table('users')->updateOrInsert(
                ['email' => 'test.student@student.passerellesnumeriques.org'],
                [
                    'name' => 'Test Student',
                    'email' => 'test.student@student.passerellesnumeriques.org',
                    'password' => '$2y$10$92DgjTkDQWdwgtfoZ49GYO4gVmyq8HHp9SzJA0q93B4qQyL6nH5nW',
                    'role_id' => $studentRoleId,
                    'student_id' => $testStudentId,
                    'is_active' => true,
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }
}
